apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupod1
  name: ashupod1
spec:
  containers:
  - image: alpine  # name of image 
    name: ashupod1 # name of container
    command: ["/bin/sh","-c","ping 8.8.8.8"] # parent process of container 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
